on:
  push:
    tags:
      - '*'
name: Build and release on push
jobs:
  release:
    name: create release artifacts 
    runs-on: ubuntu-latest
    steps:
      - name: clone open amt examples repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Print github workspace
        run: echo $GITHUB_WORKSPACE && pwd && echo ${{ github.workspace }} 

      - name: tar zip helm directory
        shell: bash
        run: |
          (cd $GITHUB_WORKSPACE/kubernetes && tar -czvf open-amt-toolkit-helm.tar.gz charts)

      - name: upload helm tarball release artifact 
        uses: svenstaro/upload-release-action@v2 
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace}}/kubernetes/open-amt-toolkit-helm.tar.gz
          asset_name: open-amt-toolkit-helm.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "Open AMT Cloud Toolkit Helm deployment tarball asset"